### ISSUE TITLE
Save card / subscription

### ISSUE THREAD

**Issue by simplenotezy** [danielboendergaard/quickpay-v10#1]
Great library!

Is it possible to save a card to a subscription using this library? I.e. I receive a card-token form an embedded form, and I create it as a subscription and complete a payment through that subscription?

**Comment by danielboendergaard** [comment]
Yes i believe you can use the token when you authorize a subscription payment

**Comment by danielboendergaard** [comment]
Apparantly you cannot: `This is achieved by submitting the credit card data directly to QuickPay who then hands back a token that in turn can be used for payment (one payment only) using our API.`

You have to use the regular form or a payment link to get the users card information.
