### ISSUE TITLE
How to create a subscription?

### ISSUE THREAD

**Issue by simplenotezy** [danielboendergaard/quickpay-v10#3]
I have tried:

```
        $payment = $qp->subscriptions()->create([
            'currency' => 'DKK',
            'order_id' =>'some-random-id'
        ]);
```

But can't figure out what to do with the payment response. If I die and dump the `$payment` object

![image](https://cloud.githubusercontent.com/assets/3786627/12567168/d777a52a-c3bd-11e5-86d9-222c27b30141.png)

**Comment by danielboendergaard** [comment]
See this comment:
https://github.com/danielboendergaard/quickpay-v10/issues/1#issuecomment-174714607

After you have created a subscription, you use the `recurring` method

**Comment by simplenotezy** [comment]
Can you please provide a code example? I am really lost here.

I wish to save a users credit card (I guess I use `Subscription` for that?) so we can authorize on the card for future purchases without having the user to re-enter the credit-card details.

Many thanks in advance.

Tried the following without luck:

```
$subscription = $qp->subscriptions()->create([
    'currency' => 'DKK',
    'order_id' => 'some-id',
    'description' => 'some-desc',
    'merchant_id' => 'merchant-id',
    //'state' => 'new',
    'test_mode' => '1',
    'acquirer' => 'Clearhaus' // is this needed?
]);

// create recurring subscription
$recurring = $qp->subscriptions()->recurring($subscription->id, [
    //'id' => $subscription->id,
    'amount' => 'some-currency',
    'currency' => 'DKK',
    //'auto_capture' => TRUE,
]);
```

Getting error response on $recurring:

![image](https://cloud.githubusercontent.com/assets/3786627/12588185/b92b9762-c457-11e5-8196-56c1473969fd.png)

```
Validation error: Transaction in wrong state for this operation
```

**Comment by danielboendergaard** [comment]
Unfortunately you have to make the authorization using the old school form http://tech.quickpay.net/payments/form/

After that you use the `recurring` method as i mentioned.

**Comment by danielboendergaard** [comment]
I have added some documentation on subscriptions here: https://github.com/danielboendergaard/quickpay-v10#create-a-subscription-and-make-recurring-payments

**Comment by dongido001** [comment]
I got the same error.

Dropping this here for others that might face the same issue.

After hours, it turns out, you need to enable subscription on the card for it to work!

<img width="592" alt="screen shot 2018-07-05 at 3 09 59 pm" src="https://user-images.githubusercontent.com/18917158/42328358-ee4fd1ac-8065-11e8-88a0-94a31a1697ab.png">
