### ISSUE TITLE
How to get status code after response?

### ISSUE THREAD

**Issue by faysalmahamud** [danielboendergaard/quickpay-v10#9]
This is not exactly issue. 
```
		$payments = $qp->payments()->create([
		    'currency' => $currency,
		    'order_id' => $donation_id,
		]);
```
How can I get response status?

**Comment by danielboendergaard** [comment]
It's not currently supported, but an exception is thrown when a non 2xx response is received.
See details here: https://github.com/danielboendergaard/quickpay-v10/blob/master/src/Client.php#L85

**Comment by faysalmahamud** [comment]
I have fixed this own with some customization on your code. However, this is awesome quickpay api client.
